### ISSUE TITLE
Добавить сообщение для нового пользователя, если нет опубликованных постов.

### ISSUE THREAD

**Issue by alisher-matkurbanov** [khodjabekova/simple_blog#2]
**Как воспроизвести:**
- Открыть браузер в анонимном режиме (чтобы не было сохраненных сессий)
- Перейти по адресу localhost:8000/

**Какое поведение сейчас:**
Пустая страница.

**Какое поведение было бы лучше:**
Страница с сообщением, что нет опубликованных постов.

**Comment by khodjabekova** [comment]
done
