### ISSUE TITLE
Bad unique constrains in blog_post table

### ISSUE THREAD

**Issue by alisher-matkurbanov** [khodjabekova/simple_blog#5]
Why do you restrict user from creating 2 posts with same content?

Actually, If you want to do this, you need to handle this error on the validation stage.
`UNIQUE constraint failed: blog_post.author_id, blog_post.text`

But, I think it would be better to not restrict him of doing this and leave only blog_post.id unique.

**Comment by khodjabekova** [comment]
I was planned slugify the title, but now I use id, so I changed model. Now you can write post with the same titles. Watch latest commit
